name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run Maven tests
        run: mvn clean test

  CI:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build tech-tools-jsp
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USR }}/tech-tools-jsp:v${{ vars.API_VERSION }}
            ${{ secrets.DOCKERHUB_USR }}/tech-tools-jsp:latest
